version: "3.2"

services:
  prueba-api:
    image: prueba-api-db-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8086
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8084:8086
      - 10006:10009
    environment:
      - TESTING=0
      - WEB_APP_VERSION=1.0.0
      - WEB_APP_TITLE=prueba-api-db
      - WEB_APP_DESCRIPTION=Database service for Prueba-Api-Db
      - POSTGRES_DATABASE_URL=postgres://postgres:postgres@prueba-api-db:5432/prueba_api_test
      - ENVIRONMENT=prod
      - DEFAULT_EXPIRE_TIME=3600
      - DEFAULT_DATA=True
      - DEBUGGER=False
    # network_mode: host
    networks:
      - prueba-api

  prueba-api-db:
    image: prueba-api-db
    build:
      context: ../db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_prueba-api:/var/lib/postgresql/data
    networks:
      - prueba-api

volumes:
  db_prueba-api:
    external: true

networks:
  prueba-api:
    external: true
